### PR TITLE
Don't extract tar archive in tmpfs when installing from recovery

### PR DESCRIPTION
**Pull request by ata2001**
Closes: #631 (possibly)

### CODE REVIEW

**Comment by drebrez** [comment]
I can test it, will let you know the result soon.

**Comment by ata2001** [comment]
@ollieparanoid I've tested it of course, but I don't know, whether it solves the issue mentioned above, because @zhenyolka did not reply yet.

**Comment by ollieparanoid** [comment]
My bad, I forgot about #631. So we wait with the merge until @zhenyolka respons whether this fixes the issue? Or would you prefer if we merged it already, because it is an improvement even if it does not fix that issue completely?

**Comment by ata2001** [comment]
Does it really reduce memory usage?

**Comment by drebrez** [comment]
@ata2001 @ollieparanoid I tested it and it works, now the percentage stops at 4%, and continues when on screen it shows `Installing rootfs...`. Also gives a better idea of the progress. No idea about the memory usage, probably it's better now

**Comment by ollieparanoid** [comment]
I am pretty sure that the memory usage is better now. Without this PR, the archive would get extracted to `/tmp` (to RAM) first, and now it gets streamed into the tar extraction utility, one chunk at a time.

Thanks for testing @drebrez! Merging this, as it is an improvement ("gives a better idea of the progress" + memory usage). Great work, @ata2001! 🎉

**Pull request merged**
