### PR TITLE
[RX51] misc improvements

### PR DESCRIPTION
**Pull request by craftyguy**

### CODE REVIEW

**Comment by craftyguy** [comment]
@MartijnBraam have you had a chance to try any of these changes out?

**Comment by MartijnBraam** [comment]
It doesn't seem to do anything for me, not sure why

**Comment by ollieparanoid** [comment]
@MartijnBraam, what is the status on this PR? (I recall that you weren't sure whether you actually flashed it - is that true?)

**Comment by craftyguy** [comment]
@MartijnBraam 

Can you review this PR?

**Pull request merged**
