### PR TITLE
qt5-qtdeclarative (QML) compile for armv7 to enable JIT and make it work at all

### PR DESCRIPTION
**Pull request by ollieparanoid**
Works for me on `i9100`. I was able to start the hello world demo from QML with weston (it takes seconds to show up though, even with the JIT).

Thanks a lot for @magmastonealex for providing instructions on how to do this. Could you please review this implementation (other reviews also welcome)?

PS: @magmastonealex, do you mind if I add you to the GitHub project, so you can be selected as reviewer for PRs? There are no special rights attached in votes, it's only responsibility 😉 

Workaround for #878.

### CODE REVIEW

**Comment by magmastonealex** [comment]
@ollieparanoid  Looks good to me. The seconds to go from black window to first draw was the same for me - My theory is that it's related to mesa/swrast, but I have no good evidence for that.

And I certainly don't mind being added to the GitHub project!

**Comment by PureTryOut** [comment]
I guess this is fine because `qt5-qtdeclarative` didn't work on armhf before anyway right?

**Comment by ollieparanoid** [comment]
Exactly. And since this is only a workaround, the issue stays open until it is fixed properly.

**Comment by PureTryOut** [comment]
Cool! Hopefully we can fix it eventually for armv6 devices as well. It might run slower than preferred, but it shouldn't crash. I'll move back to the issue then.

**Comment by magmastonealex** [comment]
@PureTryOut There's a half-fix for armv6 devices, which is to build in debug mode. It's not a great option, as it bloats the package significantly, but it should let the interpreter work on armv6. The fact that it doesn't have the same issue in debug mode makes it rather hard to track down the actual root cause.

**Pull request merged**
