### PR TITLE
grouper: Use Unlegacy's kernel

### PR DESCRIPTION
**Pull request by Sudokamikaze**
* gcc6.patch contains all-in-one patch with required changes to build with latest GCC 6
* APKBUILD modifications by @antonok-edm

Signed-off-by: sudokamikaze <sudokamikaze@protonmail.com>

### CODE REVIEW

**Comment by ollieparanoid** [comment]
I've updated the `pkgver` to match the kernel's patchlevel according to the [Makefile](https://github.com/Unlegacy-Android/android_kernel_nvidia_tegra3/blob/stable/Makefile). Could you quickly describe the improvements with this kernel over the other one (apart from the patchlevel)?

Thanks for creating the PR @Sudokamikaze!

**Comment by antonok-edm** [comment]
@Sudokamikaze and I just found out that pmbootstrap flashed 3.1.10 to the device again. We had to fully remove the work folder to flash the updated kernel, zap didn't seem to work.
Should I open an issue for that?

**Comment by Sudokamikaze** [comment]
@ollieparanoid 
In Makefile i've disabled some errors that preventing kernel build
But we had small problem, tablet boots with older kernel, and newer kernel isn't tested. So don't merge it until we fix problems

**Comment by ollieparanoid** [comment]
> @Sudokamikaze and I just found out that pmbootstrap flashed 3.1.10 to the device again.

If you guys did not change the `pkgver` and `pkgrel`, then that's expected (the timestamp based rebuilds feature has been removed, see #1167 for reasoning and use `pmbootstrap build --force hello-world` to rebuild a package without changing the version). I've added a commit to this PR that modifies the `pkgver` and `pkgrel` to the patchlevel that is mentioned in the kernel's repository.

**Comment by mirh** [comment]
Stupid question; why don't you commit the gcc patch to unlegacy?

**Comment by zhuowei** [comment]
This kernel's build script seems to be missing a builddepend on xz? I can't build it. (Ubuntu 16.04, fresh install of pmbootstrap, using this branch, rebased onto master) Log: https://gist.github.com/zhuowei/fa1879e8689d0140fd184fb41cab287a

**Comment by Sudokamikaze** [comment]
@zhuowei I've added it already in my local copy

But tablet still doesn't boot anyway

**Comment by zhuowei** [comment]
@Sudokamikaze I'll test it on my Grouper later. Does it at least make a /proc/last_kmsg?

**Comment by Sudokamikaze** [comment]
@zhuowei 
No, nothing in /proc/

**Comment by ollieparanoid** [comment]
This might help: [Troubleshooting:boot](https://wiki.postmarketos.org/wiki/Troubleshooting:boot)

**Comment by PureTryOut** [comment]
@Sudokamikaze did your idea work out? What's the progress on this?

**Comment by Sudokamikaze** [comment]
@PureTryOut There's no progress
Tablet just don't boot

I thought it was kernel problem but it doens't. Kernel works flawlessly on android but PmOS don't boot with it

I think, there's something with "device-tree", I wanted to try to build with different ramdisk offset flags but build failed and I gave up

If you have an ideas or desire to bring UA's kernel working with PmOS - contact with me

**Comment by ollieparanoid** [comment]
@Sudokamikaze: we have created the following wiki page in the meantime, as we debugged other device's booting problems. There's a good chance that this gets you further:
https://wiki.postmarketos.org/wiki/Troubleshooting:boot

**Comment by Sudokamikaze** [comment]
@ollieparanoid Oh, thanks man, it'd save a lot of time!

**Comment by 0E800** [comment]
Issue with boots not getting past Google boot splash seem to happen if CONFIG_MODULES=y  is added. I am trying to isolate another which involves either bt_usb or mac80211

**Pull request closed without merging**
