### PR TITLE
Tf101 touch extension

### PR DESCRIPTION
**Pull request by LongnoseRob**
**This adds the data for the touchscreen to the device-asus-tf101 package.**

this is still **WIP**, as the touchscreen device gets detected, but ther is something wrong.

The touchscreen does not work in weston or in xfce4.
I have some more details from the Xorg.0.log after installing xfce4:

> 
> [   691.457] (II) config/udev: Adding input device mxt1386 (/dev/input/event0) 
> 
> [   691.458] (**) mxt1386: Applying InputClass "libinput touchscreen catchall"
> 
> [   691.458] (II) Using input driver 'libinput' for 'mxt1386'
> 
> [   691.458] (**) mxt1386: always reports core events
> 
> [   691.458] (**) Option "Device" "/dev/input/event0"
> 
> [   691.458] (**) Option "_source" "server/udev"
> 
> [   691.461] (II) event0  - (II) mxt1386: (II) is tagged by udev as: Touchscreen
> 
> [   691.462] **(EE) event0  - (EE) mxt1386: (EE) kernel bug: device has min == max on ABS_MT_TOUCH_MAJOR**
> 
> [   691.463] (II) event0  - (II) mxt1386: (II) was rejected
> 
> [   691.760] (II) event0  - not using input device '/dev/input/event0'.
> 
> [   691.760] (EE) libinput: mxt1386: Failed to create a device for /dev/input/event0
> 
> [   691.760] (EE) PreInit returned 2 for "mxt1386"
> 
> [   691.760] (II) UnloadModule: "libinput"
> 
> [   691.763] (II) config/udev: Adding input device mxt1386 (/dev/input/mouse0)
> 
> [   691.764] (II) No input driver specified, ignoring this device.
> 
> [   691.764] (II) This device may have been added with another device file.

Does anybod know what this Kernel error message means in detail?
Could it be that my touchscreen calibration data is wrong?
Could we get the touch-screen calibraton data somehow on the shell from TWRP?

Other thing I have tested sofar:
-USB support for mouse/keyboard works 
-dock keyboard works,
-dock touchpad does not work
-wifi misses firmware

### CODE REVIEW

**Comment by rrooij** [comment]
For what's it worth, the touch screen in recovery is `/dev/input/event1`.

**Comment by rrooij** [comment]
You might want to try:

```
Section "InputClass"
Identifier "elantech_touchscreen"
MatchDevicePath "/dev/input/event5"
Driver "mtrack"
EndSection
```
as `/etc/X11/xorg.conf.d/elantech-mtrack.conf` to get your dock touchpad working

**Comment by rrooij** [comment]
@LongnoseRob you can change those values with a hook. Check out some other devices on how to do this, for example the i9070 if I'm not mistaken.

You don't need my xorg config by the way. I think it's better to remove it.

If you want to try synaptics for the touchpad, run `./pmbootstrap.py install --no-fde --add 'xf86-input-synaptics'`

**Comment by LongnoseRob** [comment]
while I have not much progress  with the touchscreen, I found this kernel patach https://patchwork.kernel.org/patch/9208775/ from 2016, which could may be help us with solving this issue.

But I am not sure if  this patch would work on the 3.1.10-15 kernel we are currently using for the TF101.

**Comment by LongnoseRob** [comment]
Dear all

I will close this PR now.
Currently I donot have the time for more tinkering with the TF101 and postmarkOS.
If I should have time again to continue I will try getting a mainline kernel running and then try the touchscreen again..

Thanks for the support, I will keep monitoring this project..

**Pull request closed without merging**
