### PR TITLE
[RX51] Add support for physical events w/ acpid

### PR DESCRIPTION
**Pull request by craftyguy**
This adds a way to handle physical events like keypad slide switch,
screen lock, camera lid, and others. This uses acpid from busybox (I was
wrong about the real acpid package), and an acpi.map file to map events
to 'scripts'. The scripts are symlinked to /etc/acpi/handler.sh,
automatically by the new post-install script, where
they are handled based on which script was called. This allows for
easily adding whatever is necessary for #178.

If this PR is merged, I will create a new wiki page detailing how others
can use this framework on other devices.

### CODE REVIEW

**Comment by craftyguy** [comment]
@MartijnBraam 

Thanks for the feedback. I have discovered that it is futile to start busybox's acpid on bootup, because it starts before the kernel has finished modprobing devices (like gpio_keys) and the current implementation of busybox acpid essentially ignores any new devices that come up after it has started. I have reached out to the busybox mailinglist for further assistance (hopefully with the decision to patch it).

In the meantime, I propose that this PR is merged so I (and maybe others) can continue to implement the "not implemented" features in the acpi handler here. I have also added volume keys, headphone jack, and power button events.

**Comment by ollieparanoid** [comment]
Great work! Also how you've handled this with talking to upstream :)

If I understand you correctly, the `acpid` package is not needed anymore? In my opinion we should delete it if we have no use case for it. Otherwise it will become outdated over the time and have security holes.

In case you want to, I could open up another repository for discarded packages and move it there.

**Comment by MartijnBraam** [comment]
Well maybe the complete acpid daemon fixes the problems with busybox acpid having race conditions with loading modules.

**Comment by craftyguy** [comment]
It does, it uses inotify to monitor for new devices I believe..
however I couldn't figure out how to wire it up to the buttons/keys
since it monitors /dev/acpi (or something similar) and ARM doesn't
actually have ACPI.

**Comment by ollieparanoid** [comment]
So it doesn't make sense for our use case and we could remove the package?

**Comment by craftyguy** [comment]
I think so, but want to investigate a little more just to be sure.

**Pull request merged**
