### PR TITLE
mkbootimg: replace python version with c version.

### PR DESCRIPTION
**Pull request by lramage94**
See https://github.com/postmarketOS/pmbootstrap/issues/441

### CODE REVIEW

**Comment by drebrez** [comment]
@lramage94 @ollieparanoid this new package also provides `unpackbootimg` executable, what about removing the other `unpackbootimg` package that we have? (aports/main/unpackbootimg)

**Comment by ollieparanoid** [comment]
Good idea! We could add `provides="unpackbootimg"` to this package to make the transition easier.

**Comment by drebrez** [comment]
@ollieparanoid I'm not sure how exactly works that `provides` variable in APKBUILD, it's something like an alternative name for the same package? If there is only `mkbootimg` package and not the `unpackbootimg`, if I run `apk add unpackbootimg` it will install `mkbootimg`?

**Comment by ollieparanoid** [comment]
Yes, it would work exactly like that.

**Comment by ollieparanoid** [comment]
So I wrote a script to compare the boot.img files created by both tools, and ran it on 19 devices so far. The result is, that it is not identical for any of them. I think the order of the appended `dtb` files is different, I'll need to investigate this further. (CC @osm0sis, this might be interesting to you.)

[Here's the script.](https://gist.github.com/ollieparanoid/eb58ae612368111f2621d082363eaa1b) (If anyone wants to run this, please read it before executing it.)

**Comment by drebrez** [comment]
Does the order of `dtb` files matters?

**Comment by ollieparanoid** [comment]
I guess it does not matter for booting. But it makes it harder to tell if both files produce the same output.

**Comment by osm0sis** [comment]
It'll always be different; Google's latest mkbootimg added os_version and os_patch_level so no chance of them being the same because of the updated header. dtb files aren't added any differently than CM's source before mine.

So unfortunately it's not really a valid automated check. What matters is that they boot.

**Comment by ollieparanoid** [comment]
Right, that makes sense. Then I suggest we boot it on a hand full of devices at least, before merging it.

(I can do that later/tomorrow on my `lg-mako` (Nexus 4), would be nice if someone else could test on their devices as well.)

**Comment by ollieparanoid** [comment]
Release `0.5.0` has been tagged to easily go back:
https://github.com/postmarketOS/pmbootstrap/releases/tag/0.5.0

**Pull request merged**
