### PR TITLE
Run fast testcases in Travis CI, remove obsolete testcase

### PR DESCRIPTION
**Pull request by ollieparanoid**
* This adds `test/testcases_fast.sh`, which also gets executed by Travis CI now.
* The ones which require cross-compilers or traffic-intense setup (cloning Alpine's aports repo) are disabled for now.
* The apkindex_files cache has been removed in #345, this commit finally deletes the obsolete testcase, which has been failing since.

### CODE REVIEW

**Comment by ollieparanoid** [comment]
Interesting, two fail on Travis, but do not fail locally. I'll need some time to investigate and fix this (help welcome if anyone wants to).

**Comment by ollieparanoid** [comment]
@ata2001 @craftyguy @drebrez @kskarthik @opendata26 @PabloCastellano @pavelmachek @PureTryOut  @MartijnBraam @yuvadm @z3ntu @zhuowei:

It would be nice if you could take a look at this. The following function adds an offset to the folder size, although it should only return the size on disk as I understand it:

https://github.com/postmarketOS/pmbootstrap/blob/5e7596d3c525aa663311208d09606c8981c3604b/pmb/helpers/other.py#L26-L38

I assumed, that the offset is constant with `140` bytes, but that is not the case, as it [fails on Travis](https://travis-ci.org/postmarketOS/pmbootstrap/builds/288754759#L667):
```python
    def test_get_folder_size(args, tmpdir):
        # Write five 2 KB files to tmpdir
        tmpdir = str(tmpdir)
        files = 5
        for i in range(files):
            pmb.helpers.run.user(args, ["dd", "if=/dev/zero", "of=" +
                                        tmpdir + "/" + str(i), "bs=1K",
                                        "count=2", "conv=notrunc"])
    
        # Check if the size is correct
        # 140 bytes seem to get added by the filesystem for the directory
        size = 2048 * files + 140
>       assert pmb.helpers.other.folder_size(args, tmpdir) == size
E       AssertionError: assert 14336 == 10380
```

(This is the only failing testcase in the PR.)

**Comment by zhuowei** [comment]
@ollieparanoid https://www.gnu.org/software/coreutils/manual/html_node/du-invocation.html the --apparent-size option may help here?

**Comment by ollieparanoid** [comment]
Yeah, I also think it makes it better, I've enabled it in the last commit (updated my previous comment to show the updated code snippet). But there are still some bytes getting added to the folder for some reason :\

**Comment by drebrez** [comment]
I did some investigation and found this:
```
$ find <folder> -type f -print0 | du --files0-from=- --summarize --apparent-size --block-size=1
2048    ./111
2048    ./333
2048    ./222
2048    ./444
2048    ./555
10240   total
```
what you think?

**Comment by ollieparanoid** [comment]
@drebrez: Thanks for the idea! I've tried it, and I still get a different result on my PC compared to what you have.... I'm starting to doubt that it is possible to use `du` (which comes from "disk usage" apparently) to display the actual folder size, as if you would put it into an image file (although it says in the manpage that you can do just that with `--apparent-size` - it clearly does not work).

However, I think the roughly estimated size we get from `du` is good enough for our use case. So I've adjusted the testcase to be more tolerant with the output.

(I've commited and pushed a change, but somehow it won't show up here in GitHub...?)

**Comment by craftyguy** [comment]
I haven't actually tried this, but instead of calling du (which may not be the same version in travis vs your system vs @drebrez's system), would something like `os.walk`ing a directory in python, calling `os.path.getsize` on each file in the directory's tree to add up their sizes lead to a deterministic total directory size across environments?

**Comment by craftyguy** [comment]
lol, my suggestion might be what you are trying to change from. Sorry.

**Comment by ollieparanoid** [comment]
We also did that at some point (I think @drebrez implemented it? or I've played with it) and it turned out to be really slow compared to `du`.

**Comment by ollieparanoid** [comment]
Thanks for having a look at it!

**Pull request merged**
