### PR TITLE
linux-postmarketos-qcom: Remove composite usb gadget for networking

### PR DESCRIPTION
**Pull request by MartijnBraam**
This removes the precomposed usb gadget from the kernel config and enables the configfs usb gadget modules. This makes the usb networking on the hammerhead come up reliably

---
[x] Merge on GitHub (see <https://postmarketos.org/merge>)

### CODE REVIEW

**Comment by drebrez** [comment]
@MartijnBraam also the sony sirius uses the `linux-postmarketos-qcom` kernel, maybe someone have to check if it still works also there?

**Comment by MartijnBraam** [comment]
Yeah this definitely needs some multiple device testing

**Comment by MartijnBraam** [comment]
Hmm it looks like that's a change from running menuconfig on 4.17-rc4 while the old config was for 4.16

**Comment by MartijnBraam** [comment]
This is the least amount of changes I can get it to do with menuconfig, I'm not sure how to make the QMI_HELPER a module again, it changes it on its own when you run menuconfig without touching anything.

screenshot from 2018-05-05 13-44-47

**Comment by bhush9** [comment]
Thinking about please disable, SAMPLE_QMI_CLIENT and effectively QMI_HELPER... as those I had enabled for testing something locally and then those slipped into config for aports but those are not needed

**Comment by bhush9** [comment]
There is some super weirdness is going on, but I don't think is related to this PR, selecting weston makes it not start device at all for some reason which I believe is kernel panic/hang or something.. But I don't think it's related to this PR at all since this PR doesn't touch the graphics part at all and is good to go IMO.

**Comment by MartijnBraam** [comment]
I've bumped the pkgrel, now waiting on testting on the sirius @opendata26

**Pull request merged**
