### PR TITLE
[WIP] Initial work on sony aries

### PR DESCRIPTION
**Pull request by kskarthik**

### CODE REVIEW

**Comment by ollieparanoid** [comment]
Great work!

Currently we have the policy to put devices, where graphical output does not work, into an extra device branch.

However, it turned out, that this will have a big rebasing overhead for all changes, and these extra packages do not hurt in my opinion. So I would suggest we directly integrate this into master. Thoughts on that, everyone?

**Comment by drebrez** [comment]
@ollieparanoid maybe we can change that policy to only put devices in master with a working graphical output, since we also have to init option to not install any UI.
A suggested policy for devices in master is that at least pmOS boot and ssh (usb network) works?

**Comment by kskarthik** [comment]
@drebrez kenel compile works with telnet. No GUI yet. 

@ollieparanoid in that case, I suggest the stable device ports to `aports/device/stable` & WIP one's to `aports/device/wip` 

But again, this may need code level changes.

**Comment by kskarthik** [comment]
@drebrez kenel compile works with telnet. No GUI yet. 

@ollieparanoid in that case, I suggest the stable device ports to `aports/device/stable` & WIP one's to `aports/device/wip` 

But again, this may need code level changes.

**Comment by kskarthik** [comment]
B2G project used to maintain a separate repo for device manifests. There is a pmbootstrap type program but we can edit the repo links from where it should clone the device manifest. Its better we rip off the entire device part to a new repo & maintain it. Again, this also needs  relevant code changes.

**Comment by kskarthik** [comment]
pmbootstrap is ongoing heavy dev. Its not ideal to keep device configs inside it. 

Also, we also need to relocate the wiki. We talked about this on IRC today.

**Comment by ollieparanoid** [comment]
@kskarthik: You're completely right about the wiki and about having device configs (or rather the whole aports folder) not in the tree. See #452 and #383 respectively. I'd rather not implement support for sub-subfolders in `aports` right now, as this takes development time again and we just changed the directory structure.

@drebrez wrote:
> maybe we can change that policy to only put devices in master with a working graphical output, since we also have to init option to not install any UI.
> A suggested policy for devices in master is that at least pmOS boot and ssh (usb network) works?

That makes sense to me.
I'll throw this PR in the channel to possibly get a few more opinions, and if no one has anything against it, I would merge this to master.

**Comment by ollieparanoid** [comment]
No one complained, so I merged it. Thanks for your work on this @kskarthik!

**Comment by kskarthik** [comment]
☺

**Pull request merged**
