### PR TITLE
Fix Qemu for arm: use LTS kernel, don't offer mesa-dri-virtio

### LINKED ISSUE #1017: QEMU arm doesn't work
When running `./pmbootstrap.py qemu --arch=arm` (on a x86_64 host) I get the following error in the log.
```
(019941) [20:07:11] WARNING: Qemu is not using KVM and will run slower!
(019941) [20:07:11] % sudo chmod 666 /home/luca/.local/var/pmbootstrap/chroot_native/home/pmos/rootfs/qemu-vexpress.img
(019941) [20:07:11] NOTE: Run 'pmbootstrap qemu --image-size 2G' to set the system image size when you run out of space!
(019941) [20:07:11] Connect to the VM (telnet requires 'pmbootstrap initfs hook_add usb-shell'):
(019941) [20:07:11] * (ssh) ssh -p 2222 user@localhost
(019941) [20:07:11] * (telnet) telnet localhost 2224
(019941) [20:07:11] % qemu-system-arm -kernel /home/luca/.local/var/pmbootstrap/chroot_rootfs_qemu-vexpress/boot/vmlinuz-postmarketos-stable -initrd /home/luca/.local/var/pmbootstrap/chroot
_rootfs_qemu-vexpress/boot/initramfs-postmarketos-stable -append "console=ttyAMA0,38400n8 console=tty1 PMOS_NO_OUTPUT_REDIRECT PMOS_FORCE_PARTITION_RESIZE" -m 1024 -netdev user,id=net0,host
fwd=tcp::2222-:22,hostfwd=tcp::2224-:24,net=172.16.42.0/24,dhcpstart=172.16.42.1 -show-cursor -dtb /home/luca/.local/var/pmbootstrap/chroot_rootfs_qemu-vexpress/usr/share/dtb/vexpress-v2p-c
a9.dtb -M vexpress-a9 -sd /home/luca/.local/var/pmbootstrap/chroot_native/home/pmos/rootfs/qemu-vexpress.img -device virtio-net-device,netdev=net0 -vga virtio -display sdl,gl=on
WARNING: Image format was not specified for '/home/luca/.local/var/pmbootstrap/chroot_native/home/pmos/rootfs/qemu-vexpress.img' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.
qemu-system-arm: Virtio VGA not available
```
The same error happens when running `./pmbootstrap qemu` on an ARM board.

### PR DESCRIPTION
**Pull request by ollieparanoid**
This PR fixes #1017.

* Use the LTS kernel (just like device-qemu-amd64)
* Don't ask for the mesa driver when the Qemu arch is not the
  native arch and always use swrast in that case

**NOTE:** I recommend `--display=gtk` for arm, because then you can
see the serial output, and you can toggle between the two screens
instead of having them side by side (we only use one anyway).

---

With this PR, the boot looks like this for me:
* Few seconds of "Guest has not initialized the display (yet)"
* ~ 2 minutes of pmOS loading screen (without console text written over it, unlike `qemu-amd64`!)
  * all console messages get written to the serial output though
* ~ 2 minutes of black screen
* weston comes up

### CODE REVIEW

**Comment by z3ntu** [comment]
I can ssh into the VM but the first "pl111" output only has a black screen (before there was the boot logo). Uptime is 14 minutes now and still nothing. Logread says
```
Dec 31 23:59:59 localhost user.notice user:weston: Date: 2017-12-21 GMT
Dec 31 23:59:59 localhost user.notice user:weston: [17:58:48.019] weston 3.0.0
Dec 31 23:59:59 localhost user.notice user:weston:                http://wayland.freedesktop.org
Dec 31 23:59:59 localhost user.notice user:weston:                Bug reports to: https://bugs.freedesktop.org/enter_bug.cgi?product=Wayland&component=weston&version=3.0.0
Dec 31 23:59:59 localhost user.notice user:weston:                Build: unknown (not built from git or tarball)
Dec 31 23:59:59 localhost user.notice user:weston: [17:58:48.042] Command line: /usr/bin/weston -c /etc/xdg/weston/weston.ini.default
Dec 31 23:59:59 localhost user.notice user:weston: [17:58:48.044] OS: Linux, 4.9.65, #1-postmarketOS PREEMPT Fri Dec 1 20:15:03 GMT 2017, armv7l
Dec 31 23:59:59 localhost user.notice user:weston: [17:58:48.098] Using config file '/etc/xdg/weston/weston.ini.default'
Dec 31 23:59:59 localhost user.notice user:weston: [17:58:48.118] Output repaint window is 7 ms maximum.
Dec 31 23:59:59 localhost user.notice user:weston: [17:58:48.133] Loading module '/usr/lib/libweston-3/fbdev-backend.so'
Dec 31 23:59:59 localhost user.notice user:weston: [17:58:48.208] initializing fbdev backend
Dec 31 23:59:59 localhost user.notice user:weston: [17:58:48.222] Creating fbdev output.
Dec 31 23:59:59 localhost user.notice user:weston: [17:58:48.224] Opening fbdev frame buffer.
Dec 31 23:59:59 localhost user.notice user:weston: [17:58:48.226] Calculating pixman format from:
Dec 31 23:59:59 localhost user.notice user:weston:                 - type: 0 (aux: 0)
Dec 31 23:59:59 localhost user.notice user:weston:                 - visual: 2
Dec 31 23:59:59 localhost user.notice user:weston:                 - bpp: 16 (grayscale: 0)
Dec 31 23:59:59 localhost user.notice user:weston:                 - red: offset: 11, length: 5, MSB: 0
Dec 31 23:59:59 localhost user.notice user:weston:                 - green: offset: 5, length: 6, MSB: 0
Dec 31 23:59:59 localhost user.notice user:weston:                 - blue: offset: 0, length: 5, MSB: 0
Dec 31 23:59:59 localhost user.notice user:weston:                 - transp: offset: 0, length: 0, MSB: 0
Dec 31 23:59:59 localhost user.notice user:weston:                 - pixman_type: 0
Dec 31 23:59:59 localhost user.notice user:weston: [17:58:48.234] Type guessed: 2:
Dec 31 23:59:59 localhost user.notice user:weston: [17:58:48.262] warning: no input devices on entering Weston. Possible causes:
Dec 31 23:59:59 localhost user.notice user:weston:      - no permissions to read /dev/input/event*
Dec 31 23:59:59 localhost user.notice user:weston:      - seats misconfigured (Weston backend option 'seat', udev device property ID_SEAT)
Dec 31 23:59:59 localhost user.notice user:weston: [17:58:48.276] Opening fbdev frame buffer.
Dec 31 23:59:59 localhost user.notice user:weston: [17:58:48.277] Calculating pixman format from:
Dec 31 23:59:59 localhost user.notice user:weston:                 - type: 0 (aux: 0)
Dec 31 23:59:59 localhost user.notice user:weston:                 - visual: 2
Dec 31 23:59:59 localhost user.notice user:weston:                 - bpp: 16 (grayscale: 0)
Dec 31 23:59:59 localhost user.notice user:weston:                 - red: offset: 11, length: 5, MSB: 0
Dec 31 23:59:59 localhost user.notice user:weston:                 - green: offset: 5, length: 6, MSB: 0
Dec 31 23:59:59 localhost user.notice user:weston:                 - blue: offset: 0, length: 5, MSB: 0
Dec 31 23:59:59 localhost user.notice user:weston:                 - transp: offset: 0, length: 0, MSB: 0
Dec 31 23:59:59 localhost user.notice user:weston:                 - pixman_type: 0
Dec 31 23:59:59 localhost user.notice user:weston: [17:58:48.284] Type guessed: 2:
Dec 31 23:59:59 localhost user.notice user:weston: [17:58:48.284] Mapping fbdev frame buffer.
Dec 31 23:59:59 localhost user.notice user:weston: [17:58:48.286] fbdev output 1024×768 px
Dec 31 23:59:59 localhost user.notice user:weston:                guessing 65 Hz and 96 dpi
Dec 31 23:59:59 localhost user.notice user:weston: [17:58:48.287] Compositor capabilities:
Dec 31 23:59:59 localhost user.notice user:weston:                arbitrary surface rotation: yes
Dec 31 23:59:59 localhost user.notice user:weston:                screen capture uses y-flip: yes
Dec 31 23:59:59 localhost user.notice user:weston:                presentation clock: CLOCK_MONOTONIC_RAW, id 4
Dec 31 23:59:59 localhost user.notice user:weston:                presentation clock resolution: 0.000000001 s
Dec 31 23:59:59 localhost user.notice user:weston: [17:58:48.324] Loading module '/usr/lib/weston/desktop-shell.so'
Dec 31 23:59:59 localhost user.notice user:weston: [17:58:48.509] launching '/usr/lib/weston/weston-keyboard'
Dec 31 23:59:59 localhost user.notice user:weston: [17:58:48.553] Loading module '/usr/lib/libweston-3/xwayland.so'
Dec 31 23:59:59 localhost user.notice user:weston: [17:58:50.777] Registered plugin API 'weston_xwayland_v1' of size 16
Dec 31 23:59:59 localhost user.notice user:weston: [17:58:50.779] Registered plugin API 'weston_xwayland_surface_v1' of size 8
Dec 31 23:59:59 localhost user.notice user:weston: [17:58:50.785] xserver listening on display :0
Dec 31 23:59:59 localhost user.notice user:weston: [17:58:50.799] launching '/usr/lib/weston/weston-desktop-shell'
Dec 31 23:59:59 localhost user.notice user:weston: could not load cursor 'dnd-move'
Dec 31 23:59:59 localhost user.notice user:weston: could not load cursor 'dnd-copy'
Dec 31 23:59:59 localhost user.notice user:weston: could not load cursor 'dnd-none'
Dec 31 23:59:59 localhost user.notice user:weston: could not load cursor 'dnd-move'
Dec 31 23:59:59 localhost user.notice user:weston: could not load cursor 'dnd-copy'
Dec 31 23:59:59 localhost user.notice user:weston: could not load cursor 'dnd-none'
Dec 31 23:59:59 localhost user.notice user:weston: [17:58:56.476] Spawned Xwayland server, pid 1311
Dec 31 23:59:59 localhost user.notice user:weston: Disabling glamor and dri3, EGL setup failed
Dec 31 23:59:59 localhost user.notice user:weston: Failed to initialize glamor, falling back to sw
Dec 31 23:59:59 localhost user.notice user:weston: [17:59:29.217] xfixes version: 5.0
Dec 31 23:59:59 localhost user.notice user:weston: [17:59:29.616] created wm, root 608
```

**Comment by zhuowei** [comment]
@ollieparanoid do you need to use the LTS kernel for ARM64 as well?

**Comment by ollieparanoid** [comment]
@z3ntu: it's known that the mouse does not work, see [the device page](https://wiki.postmarketos.org/wiki/QEMU_ARM_(qemu-vexpress))

@zhuowei: probably, TBH I have not tested it yet. Good that you're pointing this out. We could check/fix it within this PR, or with another one, what would you prefer?

**Comment by zhuowei** [comment]
@ollieparanoid I tried running from this PR with a fresh pmbootstrap work folder. I chose qemu-vexpress, and got this during install:

```
(003310) [21:38:54] (rootfs_qemu-vexpress) % getent passwd user
(003310) [21:38:54] (rootfs_qemu-vexpress) % adduser -D -u 1000 user
(003310) [21:38:54] (rootfs_qemu-vexpress) % addgroup user wheel
(003310) [21:38:54] ERROR: 'Namespace' object has no attribute 'qemu_mesa_driver'
(003310) [21:38:54] Run 'pmbootstrap log' for details.
(003310) [21:38:54] See also: <https://postmarketos.org/troubleshooting>
(003310) [21:38:54] Traceback (most recent call last):
  File "/media/zhuowei/redhd/docs/repos/pmbootstrap/pmb/__init__.py", line 59, in main
    getattr(frontend, args.action)(args)
  File "/media/zhuowei/redhd/docs/repos/pmbootstrap/pmb/helpers/frontend.py", line 201, in install
    pmb.install.install(args)
  File "/media/zhuowei/redhd/docs/repos/pmbootstrap/pmb/install/install.py", line 311, in install
    install_packages += ["mesa-" + args.qemu_mesa_driver]
AttributeError: 'Namespace' object has no attribute 'qemu_mesa_driver'
```

My config:
```
[pmbootstrap]
ccache_size = 5G
device = qemu-vexpress
user = user
work = /media/zhuowei/redhd/docs/vexpress-pmbootstrap
qemu_native_mesa_driver = dri-virtio
timestamp_based_rebuild = True
jobs = 4
extra_packages = none
keymap = 
ui = weston
timezone = GMT
```

Should `qemu_mesa_driver` be changed to qemu_native_mesa_driver or something?

**Comment by ollieparanoid** [comment]
Thanks for testing @zhuowei! Yes, the variable was changed to `qemu_native_mesa_driver` - and it looks like it was not replaced properly in the `pmbootstrap install` code. Also it should have always installed `mesa-dri-swrast` for the arm Qemu version. I guess the display stays black for you, because you have `mesa-dri-virtio` installed now (as in your config).

I'm focusing on the blog post now, if someone wants to fix this PR up it would be appreciated. It shouldn't be that much to do - otherwise I'll do it myself some time after the post.

**Comment by ollieparanoid** [comment]
Alright, this PR should be good to go now. Things I have done:
* Rebased the PR
* Fixed the bug that @zhuowei found
* Made sure that `qemu-vexpress` still boots. The full boot takes me 5 minutes (!), of which about 2 minutes are just a black screen right before Weston comes up. I thought it was related to me moving between workspaces or connecting to SSH (entropy? but haveged runs) or what not, so I checked it 4 times, each time with deleting the image and installing again. The 4th time I really waited the time and did not do anything, so I can confirm that it **shows up correctly after that time passed.**
* Tested `qemu-aarch64`. Framebuffer is broken, but I've configured it to use `drm` now and that works to get Weston up. It even works with the `linux-postmarketos-stable` kernel (which has been updated in the meantime - maybe it would work for the other qemu devices as well, but that is another issue). Interestingly the boot time for `aarch64` is only 2 minutes on my PC.
* Updated the [vexpress](https://wiki.postmarketos.org/wiki/QEMU_ARM_(qemu-vexpress)) wiki page, created a wiki page for [aarch64](https://wiki.postmarketos.org/wiki/QEMU_aarch64_(qemu-aarch64_))

Could someone please review the code?
Thanks!

**Comment by ollieparanoid** [comment]
Thanks @z3ntu and @zhuowei for testing and reviewing!

**Pull request merged**
