### PR TITLE
Add support for the Samsung Galaxy S5 Mini (kminilte)

### PR DESCRIPTION
**Pull request by george99g**
Added support for the [Samsung Galaxy S5 Mini](https://wiki.postmarketos.org/wiki/Samsung_Galaxy_S5_mini_(samsung-g800f)).

It successfully booted and started the SSH server. Networking over USB worked. I haven't tested the WiFi. The charging app managed to start successfully. Weston started with a working touchscreen interface.
~~Haven't tested much else, though, mainly because it decided to get stuck in a bootloop, despite working fine beforehand.~~ Fixed.

Pictures:
p1030885
p1030889
---
[x] Merge on GitHub (see <https://postmarketos.org/merge>)

### CODE REVIEW

**Comment by george99g** [comment]
The bootloop seems to be caused by a kernel panic from a camera module. I'll see if I can disable that and try booting.

**Comment by george99g** [comment]
That fixed it.

**Comment by george99g** [comment]
All of the demos on Weston work correctly.

xfce doesn't seem to be working correctly. It launches to a black screen on boot. Killing xinit flickers the desktop for a second and it returns to the black screen. It's throwing a low battery warning while the battery's almost completely charged.

MATE has the same issue, except without the battery warning.

Plasma Mobile starts up for a few seconds and then the screen turns black.

I'm getting output for the physical and capacitive keys from the input devices.

**Comment by ollieparanoid** [comment]
The Plasma Mobile issue is known, it requires accelerated hardware to work properly. Regarding the X11 issues, you could take a look at the logs by executing `logread` after connecting via SSH. To analyze this further, I'd recommend to make a new issue.

Thanks for the PR @george99g, and it's great that you've figured out how to fix the reboot loops! :tada:

**Comment by george99g** [comment]
> To analyze this further, I'd recommend to make a new issue.

Will do! Thanks for all the help so far.

**Pull request merged**
