### PR TITLE
Changed telnetd ip in boot process to 172.16.42.1/24, see issue #70

### PR DESCRIPTION
**Pull request by MartijnBraam**
I changed the subnet to the one I proposed on IRC and updated the splash screen with the new address

### CODE REVIEW

**Comment by ollieparanoid** [comment]
Thank you :+1:

**Comment by ollieparanoid** [comment]
(I've only seen this afterwards, the `APKBUILD` was not adjusted yet (bump the `pkgrel` and run `pmbootstrap checksum postmarketos-mkinitfs` to generate new checksums, as in 4b903b7232cdd25e31c7449675f734dfefc833f9)).

**Comment by MartijnBraam** [comment]
Oops, it's probably possible to make a check for this with github hooks

**Comment by ollieparanoid** [comment]
Ideally we'd build all changed aports in every pull request, like Alpine does :)
I'll try to set this up in the future, once we have binary packages.

**Pull request merged**
