### PR TITLE
remove 3d driver support for now, so MSM framebuffer works

### PR DESCRIPTION
**Pull request by lawl**
Some more work to be done here, calibration and setting the mode, but with this kernel config change that's doable. My display is pretty broken so I leave that to the main hammerhead guys.

### CODE REVIEW

**Comment by MartijnBraam** [comment]
I'm trying this build now, will merge if it works

**Comment by MartijnBraam** [comment]
This works on my hammerhead, but it has the same color mode bug as the mako (red screen).

@ollieparanoid Is this enough to merge hammerhead into mainline pmos?

**Comment by lawl** [comment]
To add, there is currently a bug where if you execute `cat /sys/class/graphics/fb0/modes > /sys/class/graphics/fb0/mode` exactly one frame is drawn, and the screen isn't updated otherwise.

@MartijnBraam found out that `while [ ! ]; do cat /sys/class/graphics/fb0/modes > /sys/class/graphics/fb0/mode; done` does achieve a stable 60fps, but that's probably not what we want to ship :P

**Comment by ollieparanoid** [comment]
Congratulations \o/ ready for mainline pmOS (I'd consider devices ready as soon as telnet works, and the deviceinfo and APKBUILD look fine)!
That while true thing is hilarious :D

**Comment by ShalokShalom** [comment]
Since this is merged, this wiki entry could be updated, yeah?
https://wiki.postmarketos.org/wiki/Google_Nexus_5_(lg-hammerhead)

**Comment by ollieparanoid** [comment]
Hi there!
What exactly on the wiki page?

**Comment by ShalokShalom** [comment]
That there is a ugly patch needed?

**Comment by ollieparanoid** [comment]
Ah I see what you mean now, the "ugly hacks" text links to this issue. Well, the hack *is* this PR, and it's used, so as I see it the link still makes sense.
There has been some good progress on [mainlining](https://postmarketos.org/blog/2017/12/31/219-days-of-postmarketOS/#mainline-linux-kernel) the hammerhead though, which wouldn't need such hacks anymore and would use the open freedreno video driver.

**Comment by ShalokShalom** [comment]
Thanks a lot

**Pull request merged**
