### PR TITLE
Mainlines amazon-thor

### PR DESCRIPTION
**Pull request by MoreRobustThanYou**
- [ ] Get ```linux-postmarketos-mainline``` to compile a working dt.img
- [ ] Get amazon-thor to boot
- [ ] Get wifi and maybe bluetooth working

### CODE REVIEW

**Comment by MoreRobustThanYou** [comment]
So it turns out, getting mainline compilation to build dt.img is a pain in the ass

**Comment by z3ntu** [comment]
@MoreRobustThanYou My device (FP2) uses qcdt (so dt.img) on downstream kernel but it works great with just appended dtb on mainline (`cat arch/arm/boot/zImage arch/arm/boot/dts/qcom-msm8974-fairphone-fp2.dtb > ../zImage-dtb`) so it could also work for you?

**Comment by MoreRobustThanYou** [comment]
@z3ntu No. For example, my device freaks out when I try to boot from a boot.img without the proper DTBs / QCDT

**Comment by MoreRobustThanYou** [comment]
Wtf

```
(006424) [14:54:56] % tail -f /home/cat/.local/var/pmbootstrap/log.txt -n 60
(006424) [14:54:56] *** output passed to pmbootstrap stdout, not to this log ***
==> initramfs: creating /boot/initramfs-postmarketos-mainline-extra
(005892) [14:54:57]  *** SET LOGIN PASSWORD FOR: 'thor' ***
(005892) [14:54:57] (rootfs_amazon-thor) % passwd thor
(005892) [14:54:57] *** output passed to pmbootstrap stdout, not to this log ***
(005892) [14:55:01] NOTE: No valid keymap specified for device
(005892) [14:55:01] (rootfs_amazon-thor) % setup-timezone -z GMT
(005892) [14:55:10] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(005892) [14:55:10] NOTE: The failed command's output is above the ^^^ line in the logfile: /home/cat/.local/var/pmbootstrap/log.txt
(005892) [14:55:10] ERROR: Command failed: (rootfs_amazon-thor) % setup-timezone -z GMT
(005892) [14:55:10] Run 'pmbootstrap log' for details.
(005892) [14:55:10] See also: <https://postmarketos.org/troubleshooting>
(005892) [14:55:10] Traceback (most recent call last):
  File "/home/cat/gitstuff/_MAINLINE/pmbootstrap/pmb/helpers/run.py", line 53, in core
    stderr=args.logfd)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sudo', '/bin/sh', '-c', "env -i CHARSET=UTF-8 PATH=/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin SHELL=/bin/ash HISTFILE=~/.ash_history /usr/sbin/chroot /home/cat/.local/var/pmbootstrap/chroot_rootfs_amazon-thor sh -c 'cd /;setup-timezone -z GMT'"]' returned non-zero exit status 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cat/gitstuff/_MAINLINE/pmbootstrap/pmb/__init__.py", line 58, in main
    getattr(frontend, args.action)(args)
  File "/home/cat/gitstuff/_MAINLINE/pmbootstrap/pmb/helpers/frontend.py", line 145, in install
    pmb.install.install(args)
  File "/home/cat/gitstuff/_MAINLINE/pmbootstrap/pmb/install/install.py", line 322, in install
    pmb.chroot.root(args, ["setup-timezone", "-z", args.timezone], suffix)
  File "/home/cat/gitstuff/_MAINLINE/pmbootstrap/pmb/chroot/root.py", line 86, in root
    return_stdout, check)
  File "/home/cat/gitstuff/_MAINLINE/pmbootstrap/pmb/helpers/run.py", line 66, in core
    raise RuntimeError("Command failed: " + log_message) from exc
RuntimeError: Command failed: (rootfs_amazon-thor) % setup-timezone -z GMT

```

**Comment by MoreRobustThanYou** [comment]
Ok, so it finally compiles... but thor refuses to boot it.

**Comment by MoreRobustThanYou** [comment]
I'm gonna close this until I make more progress

**Pull request closed without merging**
