### PR TITLE
Packaging timekeep

### PR DESCRIPTION
**Pull request by z3ntu**
Contains partly as the branch for #806 but I like these Makefiles (which
are from Debian) more. :)

For issue #793

### CODE REVIEW

**Comment by opendata26** [comment]
You would need to change the ATC file path to somewhere else, the property_functions should probably  save to a file and the time would have to be set before first run (probably using openntpd)

**Comment by ollieparanoid** [comment]
## Makefiles

* In general it would be good if the individual C files were compiled to objects, otherwise distcc will not be used, so everything will be compiled in Qemu which is a lot slower.

* I'd be very interested in the source of the Makefiles, I didn't know that someone already packaged them for Debian!

* It's great that you got it to compile, that means that the Android dependencies are packaged in a way, that they are usable and this is probably what we'll need for the android-rild.

## Do we need to package it that way?

[`timekeep.c`](https://github.com/sonyxperiadev/timekeep/blob/master/timekeep.c) seems to be really simple, so I wonder if it is worth depending on all the android specific code for that. All it seems to do is reading the time from `/sys/class/rtc/rtc0/since_epoch`, write to `/data/time/ats_2` and use property_get/property_set to sync the value to `persist.sys.timeadjust` (which is even patched out).


## Alternative approach

### Reading and writing with hwclock

Usually one would use `hwclock` to set the hardware time in a Linux distribution, and pass the real time clock device with the `-f` parameter. So I recommend doing that, and I expect that only reading works, but not writing. As it says in the [README.md](https://github.com/sonyxperiadev/timekeep/blob/master/README.md):

> TimeKeep is a small utility to keep track of time & date since the **RTC driver** on Qualcomm chipset is **read-only.**

It would be something like `hwclock -r -f /sys/class/rtc/rtc0/device` to read, and `hwclock -w -f /sys/class/rtc/rtc0/device`.

### Wrting manually, like timekeep does it

So to se the time, we need to write to `/data/time/ats_2` as I understand it, and the realtime clock will pick it up then. Right now I don't think we mount the `/data` partition, it would be great if someone could boot into TWRP/Android and check which partition it belongs to.

With that information, we should also be able to mount it, and then I would try to write the time to the file, and checking if it worked by reading it with hwclock again.


### Packaging

If all the manual steps are working, we could provide a shell-script (or C program) as wrapper for hwclock, that calls busybox' hwclock for reading and does the non-standard way of writing manually. That, together with an appropriate fstab entry and with enabling the hwclock service at boot (in a post install script) could go into an extra package, `qualcomm-hwclock-workaround`, on which the Qualcomm devices could then depend on.


## Conclusion
As it is right now, I would rather not merge it, because timekeep doesn't really do anything with the patched out code. But with some further brainstorming and testing we should be able to figure out a good way to integrate the functionallity.

Thank you very much for packaging this, I'm sure we can use the efforts somehow, especially your work on the dependencies, which are shard with `android-rild`!

**Comment by ollieparanoid** [comment]
No progress in more than 2 months. Feel free to reopen when you're working on this again.

**Comment by bhush9** [comment]
Btw, for next person reading this: there is https://github.com/ubports/timekeeper which doesn't use android_properties and standard libc and it keeps the timestmap in file in /data/time/timekeep (which can be compile time selected).

**Pull request closed without merging**
