### PR TITLE
Add device Samsung Galaxy S5 (samsung-klte)

### PR DESCRIPTION
**Pull request by drebrez**
== What works ==

* Kernel compilation
* Flash Kernel (<code>pmbootstrap flasher flash_kernel</code>)
* Flash System (<code>pmbootstrap flasher flash_system</code>)
* Initramfs boot
* USB Network
* SSH Connectivity
* Touchscreen

There is a patch for the framebuffer to revert the official behavior of not reserving/allocating the memory for it. 
The `/dev/fb0` gets created successfully and reading/writing into it works fine, but the display keeps showing the samsung logo. 
My guess is that the `msm-fb-refresher` is needed but when started the screen goes blank and the kmsg keep showing `IOMMU page fault` errors.

I'm also trying to run the mainline kernel but for the moment I've only got a shell with the serial output (no eMMC, no usb, no everything)

UPDATE: screen finally works, had to change kernel repository, add msm-fb-refresher and the weston red screen workaround

https://wiki.postmarketos.org/images/1/1b/Samsung-s5-weston.jpg

### CODE REVIEW

**Comment by drebrez** [comment]
@ollieparanoid yes I'm trying to fix the display. Actually the patch I pushed to fix the memory reservation doesn't really work, just figured out a proper fix for that.
I'm currently patching all the kernel mdss driver files to add additional logs but it's quite hard to detect where exactly it triggers the page fault.
If someone know how the kernel handles the memory and can help me, would be great. (ref: memory allocation [here](https://github.com/SmartPack/Stock-Kernel_Linaro-UBERTC_kltexxx/blob/Nougat/drivers/video/msm/mdss/mdss_fb.c#L1687-L1699))

**Comment by ollieparanoid** [comment]
@opendata26, @pavelmachek: if you guys have time, maybe you could take a look at @drebrez emmc issues with mainline?

**Comment by drebrez** [comment]
With the mainline kernel I have some issues configuring the regulator nodes.
 I'm trying to make the framebuffer driver work at least in the downstream kernel and it's there that I have the page fault issue.
Here is the relevant part in the kmesg with the additional logs I've added:
```
[  366.337948] mdss_fb_pan_display_ex: DEBUG: mdss_fb_pan_display_ex info->fix.xpanstep
[  366.337952] mdss_fb_pan_display_ex: DEBUG: mdss_fb_pan_display_ex info->fix.ypanstep
[  366.337956] mdss_fb_pan_display_ex: DEBUG: mdss_fb_pan_display_ex info->var.xoffset = 0
[  366.337960] mdss_fb_pan_display_ex: DEBUG: mdss_fb_pan_display_ex info->var.yoffset = 0
[  366.337969] mdss_fb_pan_display_ex: DEBUG: mdss_fb_pan_display_ex wait_for_finish
[  366.337973] mdss_fb_pan_display_ex: DEBUG: mdss_fb_pan_display_ex calling mdss_fb_pan_idle...
[  366.337978] mdss_fb_pan_display_sub: DEBUG: mdss_fb_pan_display_sub
[  366.337983] mdss_fb_pan_display_sub: DEBUG: mdss_fb_pan_display_sub: calling mfd->mdp.dma_fnc...
[  366.338000] samsung_dsi_panel_event_handler : unknown event (1)
[  366.339696] mdss_iommu_ctrl: mdss_mdp_overlay_pan_display+0x14c/0x360: enable 1 mdata->iommu_ref_cnt 0
[  366.341799] mdss_dsi_on:1040 Panel already on.
[  366.341809] mdss_dsi_panel_on : ++
[  366.341813] mdss_dsi_panel_on DSI_MODE = 1 ++
[  366.341817] mdss_dsi_panel_on: ctrl=e7773010 ndx=0
[  366.341821] DEBUG: mdss_dsi_panel_on: calling mipi_samsung_manufacture_id...
[  366.341825] DEBUG: mipi_samsung_manufacture_id: calling get_lcd_id...
[  366.341830] DEBUG: mipi_samsung_manufacture_id: calling get_lcd_attached...
[  366.341834] DEBUG: mipi_samsung_manufacture_id: manufacture_id_cmds.num_of_cmds = 3
[  366.341839] DEBUG: mipi_samsung_manufacture_id: calling mdss_dsi_cmd_receive...
[  366.341843] DEBUG: mdss_dsi_cmd_receive
[  366.341846] DEBUG: mdss_dsi_cmd_receive: calling get_lcd_id...
[  366.341849] DEBUG: mdss_dsi_cmd_receive: calling get_lcd_attached...
[  366.341852] DEBUG: mdss_dsi_cmd_receive: calling kmalloc rlen=4
[  366.341856] DEBUG: mdss_dsi_cmd_receive: calling mdss_dsi_cmdlist_put...
[  366.341861] DEBUG: mdss_dsi_cmdlist_commit
[  366.341864] DEBUG: mdss_dsi_cmdlist_commit: calling mdss_get_sd_client_cnt...
[  366.341867] DEBUG: mdss_dsi_cmdlist_commit: calling mdss_mdp_clk_ctrl...
[  366.341871] DEBUG: mdss_dsi_cmdlist_commit: calling mdss_dsi_cmdlist_get...
[  366.341875] DEBUG: mdss_dsi_cmdlist_commit: calling mdss_dsi_cmd_mdp_busy...
[  366.341880] mdss_dsi_cmdlist_commit:  from_mdp=0 pid=18013
[  366.341883] DEBUG: mdss_dsi_cmdlist_commit: calling mdss_bus_bandwidth_ctrl...
[  366.341888] DEBUG: mdss_dsi_cmdlist_commit: calling mdss_bus_scale_set_quota...
[  366.341892] mdss_dsi_cmdlist_commit:  from_mdp=0 pid=18013
[  366.341895] DEBUG: mdss_dsi_cmdlist_commit: calling mdss_dsi_clk_ctrl...
[  366.343634] DEBUG: mdss_dsi_cmdlist_commit: calling mdss_iommu_ctrl(1)...
[  366.343642] mdss_iommu_ctrl: mdss_dsi_cmdlist_commit+0x2dc/0x490: enable 1 mdata->iommu_ref_cnt 1
[  366.343646] DEBUG: mdss_dsi_cmdlist_commit: calling mdss_dsi_cmdlist_rx...
[  366.343814] msm_iommu_v1: Unexpected IOMMU page fault!
[  366.343818] msm_iommu_v1: name = mdp_iommu
[  366.343821] msm_iommu_v1: context = mdp_0 (0)
[  366.343823] msm_iommu_v1: Interesting registers:
[  366.343850] msm_iommu_v1: FAR    = 0000000001f20000
[  366.343853] msm_iommu_v1: PAR    = 0000000000000000
[  366.343857] msm_iommu_v1: FSR    = 00000010 [EF ]
[  366.343860] msm_iommu_v1: FSYNR0 = 00000581    FSYNR1 = 000b0007
[  366.343863] msm_iommu_v1: TTBR0  = 0000000026f6006a
[  366.343865] msm_iommu_v1: TTBR1  = 0000000000000000
[  366.343868] msm_iommu_v1: SCTLR  = 00001043    ACTLR  = 70000000
[  366.343872] msm_iommu_v1: PRRR   = ff0a81a8    NMRR   = 40e040e0
[  366.344003] msm_iommu_v1: Unexpected IOMMU page fault!
[  366.344007] msm_iommu_v1: name = mdp_iommu
[  366.344009] msm_iommu_v1: context = mdp_0 (0)
[  366.344012] msm_iommu_v1: Interesting registers:
[  366.344037] msm_iommu_v1: FAR    = 0000000001f20000
[  366.344040] msm_iommu_v1: PAR    = 0000000000000000
[  366.344043] msm_iommu_v1: FSR    = 00000010 [EF ]
[  366.344046] msm_iommu_v1: FSYNR0 = 00000581    FSYNR1 = 000b0007
[  366.344049] msm_iommu_v1: TTBR0  = 0000000026f6006a
[  366.344052] msm_iommu_v1: TTBR1  = 0000000000000000
[  366.344055] msm_iommu_v1: SCTLR  = 00001043    ACTLR  = 70000000
[  366.344058] msm_iommu_v1: PRRR   = ff0a81a8    NMRR   = 40e040e0
[  366.344076] mdss_dsi_cmds_rx:Invalid response cmd :len=0 dlen=4 diff=1
[  366.344080] DEBUG: mdss_dsi_cmdlist_commit: calling mdss_iommu_ctrl(0)...
[  366.344087] mdss_iommu_ctrl: mdss_dsi_cmdlist_commit+0x38c/0x490: enable 0 mdata->iommu_ref_cnt 2
[  366.344090] DEBUG: mdss_dsi_cmdlist_commit: calling mdss_dsi_clk_ctrl...
[  366.344124] DEBUG: mdss_dsi_cmdlist_commit: calling mdss_bus_scale_set_quota...
[  366.344129] DEBUG: mdss_dsi_cmdlist_commit: calling mdss_bus_bandwidth_ctrl...
[  366.345003] DEBUG: mdss_dsi_cmdlist_commit: calling mdss_mdp_clk_ctrl...
[  366.345010] mipi_samsung_manufacture_id: manufacture_id1=0
[  366.345013] DEBUG: mdss_dsi_cmd_receive
```

**Comment by pavelmachek** [comment]
> @opendata26, @pavelmachek: if you guys have time, maybe you could take a look at @drebrez emmc issues with mainline?

I'm sorry, I don't think I have nearly enough experience with that
hardware.

If something does not work with mainline, recommended first step is to
contact person listed in the MAINTAINERS file, cc-ing people listed by
get_maintainers.pl script.

You can also cc me, but I'm unlikely to be too helpful.

-- 
(english) http://www.livejournal.com/~pavelmachek
(cesky, pictures) http://atrey.karlin.mff.cuni.cz/~pavel/picture/horses/blog.html

**Comment by drebrez** [comment]
@ollieparanoid finally the S5 can be considered supported. I've rebased the branch to master also, let's see how travis manages to build the kernel

**Comment by ollieparanoid** [comment]
Awesome that you've fixed it, and that was a good test for the CI! The build ran through (although `apk`'s progress bars mess up the output a bit, it probably makes sense to disable the progress bars completely). Let's ship this! :ship: :tada:

**Pull request merged**
