### PR TITLE
Initial Work for HTC One M8 Port

### PR DESCRIPTION
**Pull request by fooforever**
Progress can be followed in #1206 
Kernel boots with device tree from LineageOS and can be installed by android recovery zip
Networking comes up at boot but there's not display yet

### CODE REVIEW

**Comment by PureTryOut** [comment]
Please learn how to [rebase](https://git-scm.com/book/en/v2/Git-Branching-Rebasing) your branch (rather than merging upstream changes).

The changes itself look good though.

**Comment by PureTryOut** [comment]
Note that Travis failed:

> \> Wiki device documentation
*** Pull request to master (assuming all devices boot)
htc-m8: wrong section of the wiki, this should be in booting already
*** Wiki check failed!
Thank you for porting postmarketOS to a new device! \o/
Now it's time to add some documentation:
> 1) Create a device specific wiki page as described here:
   <https://wiki.postmarketos.org/wiki/Help:Device_Page>
> 2) Add your device to the overview matrix:
   <https://wiki.postmarketos.org/wiki/Devices>
> 3) Run these tests again with an empty commit in your PR:
   $ git commit --allow-empty -m 'run tests again'

> Please take the time to do these steps. It will make your
precious porting efforts visible for others, and allow them
not only to use what you have created, but also to build upon
it more easily. Many times one person did a port with basic
functionallity, and then someone else jumped in and
contributed major new features.

**Comment by fooforever** [comment]
The documentation on the wiki say make a pull request first, I saw it failed.

**Comment by PureTryOut** [comment]
I guess we have to revise that then, thanks for mentioning it. This should be fine to merge once the page is moved to the booting section.

**Comment by fooforever** [comment]
Is there ay way these checks can be run offline? I don't know why it failed on a checksum, as far as I know my build doesn't do this.

**Comment by drebrez** [comment]
@fooforever you can run them locally, in https://github.com/postmarketOS/pmbootstrap/blob/master/.travis/travis_script.sh you can see all the script called by the builder.
Try with these two: 
- `sh test/static_code_analysis.sh`
- `sh test/testcases_fast.sh --all`

**Comment by fooforever** [comment]
The travis build seems to be failing whilst building quemu64 now, surely these changes don't even affect that ?

**Comment by PureTryOut** [comment]
They don't, the reason why it's failing now is unrelated to your PR.

```
[12:42:10] NOTE: Run 'pmbootstrap pkgrel_bump --auto' to mark packages with outdated dependencies for rebuild. This will most likely fix this issue (soname bump?).
[12:42:10] ERROR: Could not find package 'so:libcrypto.so.42' in any aports folder or APKINDEX.
```

It'll be fixed by #1400, as it's currently effecting every PR that has some kind dependency on LibreSSL.

**Comment by fooforever** [comment]
Thanks for sorting the last few bits 😊

**Pull request merged**
