### PR TITLE
temp/raspberrypi-bootloader: remove (to use Alpine's package again)

### PR DESCRIPTION
**Pull request by ollieparanoid**
This has been updated to the latest official release in Alpine, so we shouldn't need our version anymore.

@yangxuan8282: would you like to review this?

---
[x] Merge on GitHub (see <https://postmarketos.org/merge>)

### CODE REVIEW

**Comment by yangxuan8282** [comment]
@ollieparanoid 
sure, since upstream one is up to date now, we don't really need keep it anymore

**Comment by yangxuan8282** [comment]
@ollieparanoid 
after search again I found the info I provide about fixup_x.dat, start_x.elf maybe incorrect, and I have edited the comment after found it: https://github.com/postmarketOS/pmbootstrap/issues/1567#issuecomment-399749996

from raspberry pi [documents](https://www.raspberrypi.org/documentation/configuration/config-txt/boot.md): 

    start_x=1 implies start_file=start_x.elf fixup_file=fixup_x.dat
    start_x=1 should be specified when using the camera module.

so it should not related to testing version, it includes camera and software codecs

and from that pages, it can be confirmed that start_db.elf, fixup_db.dat is for debug use

although not sure if the upstream subpackage name `raspberrypi-bootloader-experimental` is related to the info I provided, but seems use `raspberrypi-bootloader-x` should better, do you think if we should inform the alpine upstream?

**Comment by ollieparanoid** [comment]
> do you think if we should inform the alpine upstream?

Sure, if you notice something like that, I think the best way is to contact Alpine devs (clandmeter in this case) directly via IRC (or e-mail, or in that GitHub issue we're using for Raspberry chatting with upstream right now). Asking via IRC also is a good method to make sure PRs does not get overlooked :+1:

**Comment by yangxuan8282** [comment]
@clandmeter would you mind check this https://github.com/postmarketOS/pmbootstrap/issues/1567#issuecomment-399749996 and this https://github.com/postmarketOS/pmbootstrap/pull/1597#issuecomment-400339404 

 the info I provide about fixup_x.dat, start_x.elf seems incorrect, maybe we should use the name `raspberrypi-bootloader-x` instead of `raspberrypi-bootloader-experimental`

**Comment by clandmeter** [comment]
I renamed it as upstream suggested it holds eXperimental features.
ref: https://github.com/raspberrypi/firmware/commit/b4ba992ff772c759cf603e00b359f9a0b4cc888e

If you found a better reference for the X naming i can make a change.

**Comment by yangxuan8282** [comment]
then seems info on elinux is correct

**Pull request merged**
