### PR TITLE
change log output order 'flash_system' before 'flash_kernel'

### PR DESCRIPTION
**Pull request by lduboeuf**

### CODE REVIEW

**Comment by ollieparanoid** [comment]
Thanks for the PR. Why did you change the order?

**Comment by lduboeuf** [comment]
if i am a noob and just follow on screen logs, i will do a flash_kernel first  and ( at least on my device ) force me to boot again in flash mode

**Comment by ollieparanoid** [comment]
That's a good reason! Alright, could you fix up the PEP8 complaints found by Travis? (you can run the `test/static_code_analysis.sh` script locally as well after installing `flake8` and `shellcheck`).

**Comment by PureTryOut** [comment]
Sorry, I'm not exactly sure why it matters what order you flash it. In my experience, it makes no difference at all, and the system will boot properly doing it either order. How does flashing the kernel first force you to boot your device into flash mode again?

**Comment by lduboeuf** [comment]
Yes, if i flash_kernel first , i can't do anything anymore in flash boot. I need to reboot and then flash_system

**Comment by PureTryOut** [comment]
Interesting. In that case, yeah the change sounds good.

**Pull request merged**
