### PR TITLE
Move aports/firmware to aports/nonfree-firmware

### LINKED ISSUE #756: Make proprietary firmware and userspace optional
The built-in wifi and baseband will not work without proprietary firmware on practically all phones. However, we could allow the user to avoid installing these blobs, just like libre distributions do it.

### Implementation idea

1. Change the device package recipes to generate the following subpackages:
* `device-vendor-name-nonfree-userland` (we don't have proprietary userland right now, so this is not needed)
* `device-vendor-name-nonfree-firmware` (depends on the firmware package(s))

(This is really easy in APKBUILDs and can be done with very few lines.)

2. Ask in `pmbootstrap init`:
```
(Explanation text)
(pkgdesc from the nonfree packages, so they can tell which hardware components they enable)
Use non-free components (none, firmware, userland, all)? [firmware]: 
```

We could directly skip the question, in case there is no nonfree subpackage for the device, and only show the firmware/userland choice when such a package exists.

3. Depending on what the user chose, the `nonfree` packages and its dependencies get built and installed in `pmbootstrap install`.

### Advantages
* Make people aware, that there are proprietary components and what they are for
* People who prefer a full libre stack can disable the firmware files which are enabled by default right now (they could use an external modem via usb etc.)
* It would allow packaging proprietary userspace drivers with libhybris (#678) in theory, while keeping it cleanly separated for users who do not wish to install them.
* Once we can run proprietary components in pmOS, it might be a lot easier to reverse engineer them.

Thoughts?

### PR DESCRIPTION
**Pull request by ollieparanoid**
Added a test case as well. When there's still an aport in the old
folder, it errors with something like:

>  The 'aports/firmware' folder has been renamed to
  'aports/nonfree-firmware'. Please move 'firmware-asus-flo',
  'firmware-adreno' to the 'aports/nonfree-firmware' folder.

Closes #756.

### CODE REVIEW

**Comment by z3ntu** [comment]
What's the advantage of having a different folder name? Isn't all firmware proprietary normally?

**Comment by ollieparanoid** [comment]
Thanks for asking! In https://github.com/postmarketOS/pmbootstrap/issues/756#issuecomment-354666117 was the plan outlined to rename `aports/firmware` to `aports/nonfree-firmware` and to create a new folder `aports/nonfree-userland` (when we actually have userland drivers packaged, e.g. for the Nokia N9).
So the name makes more sense when we will actually have the `nonfree-userland` folder.

But in theory it would be possible to have libre firmware as well, that's what @craigcomstock (aka unreasonable in #postmarketOS-lowlevel) is working in [for cellular modems](https://lists.osmocom.org/pipermail/baseband-devel/2017-December/005462.html).

I've created this PR as that was the last open TODO list entry of #756 so it can be closed. If you guys think this change doesn't make sense right now/at all, that's also fine with me, then we could scratch that.

**Comment by z3ntu** [comment]
I think currently the directory structure makes a lot of sense for the firmware packages: They are in a folder called `firmware` and are all prefixed with `firmware-`. If we are moving them to a folder called `nonfree-firmware` but still calling the package only `firmware-` is a bit weird. And also the `linux-firmware` package is called `linux-firmware` and not `linux-nonfree-firmware` :wink: So I would vote for stalling the PR until we have something that prompts this change.

**Comment by ollieparanoid** [comment]
Yeah, we won't be able to change the `linux-firmware` name in upstream.
Okay then, let's look at this again when we have a reason to.
I really appreciate your feedback, thanks again!

**Pull request closed without merging**
