### PR TITLE
Update local aports location in 'init'

### PR DESCRIPTION
**Pull request by craftyguy**
This addresses #246 by updating the local aports folder location every
time `pmbootstrap init` is called. This location would change if an
existing config file is in ~/.config and pmbootstrap's location has
changed (e.g. when switching to a different fork in a different location
on disk). With this commit, you just have to run `pmbootstrap init` and
change (or accept) the existing config values and aports location is
updated automatically.

### CODE REVIEW

**Comment by ollieparanoid** [comment]
Actually saving the aports folder in the config does not really have a benefit right now, it is more of an unwanted side-effect by how the defaults for the command line options are written.

Right now, the aports folder is always relative to the pmbootstrap folder (this may change at some point in the future, it might be cleaner to put it in an extra repository at some point).

Could you change your PR, so it does not write the aports folder into the config at all, and always uses the default (except when overridden via command line)?

Thank you for making this PR!

**Comment by craftyguy** [comment]
Sure, that's even better!

**Comment by craftyguy** [comment]
@ollieparanoid I'm now deleting the aports config before writing the config to disk, so that it is not saved in the cfg file

**Comment by ollieparanoid** [comment]
Works, thanks!

**Pull request merged**
