### PR TITLE
[linux-postmarketos] Update to 4.13

### PR DESCRIPTION
**Pull request by craftyguy**
**NOTE**: This updates linux-postmarketos from 4.12.x to 4.13.

Please test thoroughly!

An initial smoke test in QEMU and on my N900 passed, I was able to boot up, get networking, and poweroff.

Also, I do not have a device with aarch64, so I did not generate a config for this or test it.. if someone is able to test then I can create a config by accepting the defaults.

### CODE REVIEW

**Comment by ollieparanoid** [comment]
What do you expect us to test before merging this? You seem to have covered it pretty well already (QEMU and N900 are our only real-world targets for `linux-postmarketos` right now).

Thanks for upgrading again and testing!

**Comment by craftyguy** [comment]
Well, I didn't do much with qemu other than booting it.. I seem to
recall others were playing around with DRM in qemu, and networking. I
just want to make sure there are no obvious regressions. If y'all
think my testing was sufficient, then merge it!

**Comment by ollieparanoid** [comment]
@craftyguy: that makes sense, thanks for thinking about regressions for others!
If you ask me, it's good for merge.
@MartijnBraam: if you agree and no one says you shouldn't do it, then please merge it 👍

**Comment by MartijnBraam** [comment]
Trust in Linus, may his kernel be stable, hereby merged

**Comment by craftyguy** [comment]
All Hail Linus. Amen.

**Pull request merged**
