### PR TITLE
Modified Plasma launch scrict to (crudely and unreliably) detect if it has to run on the framebuffer or not

### PR DESCRIPTION
**Pull request by PureTryOut**
It would be nice if someone could test this on a non-hardware accelerated device. So far I only had the possibility to test on Qemu, which the check doesn't reliably work for (it always enters the first option).

If everything works, Plasma should appear first boot without modifications.

### CODE REVIEW

**Comment by MoreRobustThanYou** [comment]
tbh we should just add "deviceinfo_has_hardware_acceleration"

**Comment by PureTryOut** [comment]
I rather have a solid way to detect it on the device itself. `glxinfo` from the `mesa-demos` package would've been nice, but it depends on a running X server. I'd love an utility that can detect it without running either X or Wayland. Possibly we can write one ourselves?

**Comment by PureTryOut** [comment]
Well, at least I can confirm this works on my Amami's. It launches kwin succesfully first boot. I think it's good enough for now, maybe we can think of a better way to detect this in the future.

**Comment by MoreRobustThanYou** [comment]
Still doesn't work on amazon-thor. Nothing new, it didn't work before, after manually changing start_plasma.sh, either.

**Comment by PureTryOut** [comment]
No wonder, this PR only changes what you have already done manually before. It wouldn't make sense if it suddenly started working for you.

**Pull request merged**
