### PR TITLE
Upgrade weston to 3.0.0

### PR DESCRIPTION
**Pull request by PabloCastellano**
This release includes already the no_0hz_refresh_rate patch

### CODE REVIEW

**Comment by PabloCastellano** [comment]
Adding `dont_merge_pr` tag because it seems that it makes weston not to show up in qemu. Will need to investigate.

**Comment by PabloCastellano** [comment]
This is `ẁeston.log`

```
[21:17:28.390] Command line: weston
[21:17:28.390] OS: Linux, 4.13.0, #2-postmarketOS PREEMPT Tue Sep 5 20:46:08 GMT 2017, x86_64
[21:17:28.391] Using config file '/etc/xdg/weston/weston.ini'
[21:17:28.391] Output repaint window is 7 ms maximum.
[21:17:28.391] Loading module '/usr/lib/libweston-3/fbdev-backend.so'
[21:17:28.391] initializing fbdev backend
[21:17:28.391] <stdin> is already in graphics mode, is another display server running?
[21:17:28.391] fatal: fbdev backend should be run using weston-launch binary or as root
[21:17:28.391] fatal: failed to create compositor backend
```

**Comment by PabloCastellano** [comment]
After merging https://github.com/postmarketOS/pmbootstrap/pull/517, weston runs as usual

**Comment by ollieparanoid** [comment]
Nice! Has anyone tested this on a real device? (to make sure, that the fbdev backend is also working)
Also I would be interested in if this resolves #121 (weston terminal does not work).

**Comment by AeternaMia** [comment]
Hello, I tried this on `lg-mako` (Nexus 4). I got a blank screen on boot and the following weston.log:

```
[00:01:07.258] Command line: weston --pixman-type=2
[00:01:07.258] OS: Linux, 3.4.0-lineageos, #5-Alpine SMP PREEMPT Sat Sep 2 17:35:53 GMT 2017, armv7l
[00:01:07.259] Using config file '/etc/xdg/weston/weston.ini'
[00:01:07.259] Output repaint window is 7 ms maximum.
[00:01:07.259] Loading module '/usr/lib/libweston-3/fbdev-backend.so'
[00:01:07.260] initializing fbdev backend
[00:01:07.260] <stdin> is already in graphics mode, is another display server running?
[00:01:07.260] fatal: fbdev backend should be run using weston-launch binary or as root
[00:01:07.260] fatal: failed to create compositor backend
```

Note that for this device according to the wiki (https://wiki.postmarketos.org/wiki/Google_Nexus_4_(lg-mako)) it says XWayland is not supported...not sure if that means I should not have expected this to work in the first place.

**Comment by PabloCastellano** [comment]
@AeternaMia Thanks for testing!

The XWayland issue is not related. It looks like we have a regression in 3.0.0 or something to change in the weston configuration. I will review weston's changelog

**Comment by drebrez** [comment]
I also tested it, after your latest changes @PabloCastellano , but it still fails.

The output AeternaMia posted is from the second run. I disabled to start weston in the `/etc/profile.d/start_weston.sh` script and executing it manually it failed with this error:
```
Assertion failed: output->disable (libweston/compositor.c: weston_compositor_add_pending_output: 4733)
Aborted
```
running it the second time it fails with the "tty already in graphics mode" error.

see full output here => https://bpaste.net/show/80f0447b843c

**Comment by drebrez** [comment]
I think this patch (https://github.com/wayland-project/weston/commit/acd71fb0af82fb6065dd239865bd18bbbf1ceab4) fixes it, but is not included in the 3.0.0,

**Comment by PabloCastellano** [comment]
Tested with @drebrez it now works for both fbdev and drm backends!

**Comment by drebrez** [comment]
@PabloCastellano @ollieparanoid I tried to run weston using `weston-launcher` but I didn't managed to start it without root, probably I did something wrong.
I suggest closing this PR first and then investigate how to start it without root.

**Comment by ollieparanoid** [comment]
Thank you very much, @drebrez and @PabloCastellano!

**Pull request merged**
