### PR TITLE
Update Plasma to 5.12.5

### PR DESCRIPTION
**Pull request by PureTryOut**
[x] Merge on GitHub (see <https://postmarketos.org/merge>)

### CODE REVIEW

**Comment by bhush9** [comment]
Does it actually work? Because I believe there are changes in plasma-phone-components which makes it incompatible with Plasma 5.12.x releases..

**Comment by PureTryOut** [comment]
You're right, the bottom drawer stopped responding. I undid the plasma-phone-components changes, we'll wait with that till the new KDE framework and Plasma 5.13 are released.

**Comment by bhush9** [comment]
Code looks good, but travis not happy (haven't checked really where it fails)

**Comment by PureTryOut** [comment]
The builds exceed the maximum time allowed for Travis jobs. Nothing to worry about.

**Comment by ollieparanoid** [comment]
Building tested for `x86_64` and `armhf`, and it worked well. But @bhush9 hinted that we might as well delay this until the new KDE framework update:
> ollieparanoid: there will be kf5 update too so maybe postpone plasma

So I'll wait with merging this one.

**Pull request merged**
