### PR TITLE
aports: packaged matchbox-keyboard

### PR DESCRIPTION
**Pull request by drebrez**
I packaged `matchbox-keyboard` and tested it on an actual device (with hildon ui).
I've no idea why but it shows the keyboard 3 times on screen.
I've opened a terminal and tried to touch some keys and it wrote them on the terminal.
At least something works.

Closes: #655

### CODE REVIEW

**Comment by rrooij** [comment]
Works pretty good on my i9505 with XFCE4. Thanks for this! It only starts once fortunately, not three times.

**Comment by ollieparanoid** [comment]
More information about config guess / config sub [here](https://wiki.postmarketos.org/wiki/Troubleshooting#Packaging_for_aarch64:_..2Fconfig.guess:_unable_to_guess_system_type) (I've tested building for aarch64, simply because it's an older codebase and autotools based).

Thank you very much for this contribution @drebrez! 🎉 🚢 

If someone could add a photo, that would be cool.

**Comment by rrooij** [comment]
Photo

**Comment by drebrez** [comment]
@rrooij whoaa 🎉 looks good on xfce4
@ollieparanoid thanks for fixing up the packaging
on hildon maybe it's due the landscape mode, or because i'm starting it manually on the command line? no idea, @rrooij does the keyboard popup automatically when it detects an input field?

**Comment by rrooij** [comment]
@drebrez it always stays on in normal mode. I tried running it in daemon mode but it doesn't seem to recognize GTK2 text inputs as far as I could test.

**Pull request merged**
