### PR TITLE
[linux-postmarketos-mainline] update to 4.15-rc1

### PR DESCRIPTION
**Pull request by limiter121**
**Note:** This includes a fix (hack?) for #950.

### CODE REVIEW

**Comment by ollieparanoid** [comment]
@limiter121: thanks a lot for making this PR!

@ata2001, @opendata26: you're also using `linux-postmarketos-mainline` right now, could you review this PR if you have time?

**Comment by ollieparanoid** [comment]
@limiter121: while the others are using the package too, their devices do not depend yet on it, and we can't hold it back forever. do you want to update it to the current -mainline version? I'd say we merge it then.

**Comment by limiter121** [comment]
@ollieparanoid Tried to update but it doesn't work, seems to be an issue with `linux-v4.15-rc1-v4.15-rc5.patch`.

```bash
>>> linux-postmarketos-mainline: Checking sha512sums...
linux-4.14.tar.xz: OK
linux-v4.14-v4.15-rc1.patch: OK
linux-v4.15-rc1-v4.15-rc5.patch: OK
config-postmarketos-mainline.armhf: OK
config-postmarketos-mainline.aarch64: OK
config-postmarketos-mainline.x86_64: OK
001-sony-amami-dts.patch: OK
>>> linux-postmarketos-mainline: Unpacking /var/cache/distfiles/linux-4.14.tar.xz...
>>> linux-postmarketos-mainline: Applying linux-v4.14-v4.15-rc1.patch...
>>> linux-postmarketos-mainline: Applying linux-v4.15-rc1-v4.15-rc5.patch...
The next patch would empty out the file net/wireless/certs/sforshee.x509,
which is already empty!  Skipping patch.
>>> linux-postmarketos-mainline: Applying 001-sony-amami-dts.patch...
>>> ERROR: linux-postmarketos-mainline: The following patches failed:
linux-v4.15-rc1-v4.15-rc5.patch
>>> ERROR: linux-postmarketos-mainline: all failed
```

**Comment by z3ntu** [comment]
#1067 (number is exactly 100 higher than this PR ^^) updates linux-postmarketos-mainline to 4.15-rc6

**Pull request closed without merging**
