### PR TITLE
Modified postmarketos-demo as discussed on IRC:

### PR DESCRIPTION
**Pull request by moondeck**
Removed shutdown (as weston isn't running as root anymore)
Changed the firefox button to state that firefox needs to be installed

Fixes https://github.com/postmarketOS/pmbootstrap/issues/923

### CODE REVIEW

**Comment by moondeck** [comment]
That would be great... if i knew how to implement that.

**Comment by ollieparanoid** [comment]
I *think* the proper way to do this would be with `consolekit2` and sending `d-bus` messages:
https://wiki.archlinux.org/index.php/ConsoleKit#Use_D-Bus_for_power_operations

The upside is, if you could implement it that way, then it should work for XFCE4 and other desktop environments that expect it to work the same way, too. So if you want to do it that way, I recommend to test if it allows shutting down in XFCE4 etc., too (e.g. in Qemu).

We will probably need something like this in the long run anyway, so we can really shutdown as user from everywhere.

**Comment by moondeck** [comment]
Looks good. Should i just make the program execute a command like that, or is there a more elegant way to do it? I also assume we need to give the user shutdown permission by default in the build system?

**Comment by ollieparanoid** [comment]
I have edited my comment afterwards :) If you did implement it, then yes you could call the d-bus command like that. But right now we don't even start weston with consolekit2 (we start kwin with it though), so you would need to modify the weston start script etc - which would be solved more elegantly by using a real display manager such as sddm (which will probably work soon with Alpine Linux anyway).

**Comment by moondeck** [comment]
Ah, yeah, sorry, didn't see that. How about using something like nodm?

**Comment by ollieparanoid** [comment]
That one only works with X11, not with Wayland.

**Comment by moondeck** [comment]
Well, then sddm would be perfect... but what about older devices? I imagine SDDM and the whole KDE stack takes quite a bit of RAM and processor power. We could always go ahead and reinvent the wheel... but that's a task even bigger.

**Comment by ollieparanoid** [comment]
It is relatively lightweight on dependencies, and I think it doesn't load any of it at runtime if you use the autologin mode (which makes sense if you only have one user and one desktop environment). In contrary to KDM it does not depend on the KDE stack. Adelie Linux (which is also based on Alpine Linux) has packaged it [here](https://code.foxkit.us/adelie/packages/blob/master/user/sddm/APKBUILD) (it's highly likely that this gets upstreamed to Alpine later), so you can take a look at the depends and makedepends (libraries it links against are automatically added to the depends after compilation).

**Comment by moondeck** [comment]
Thanks! Should have mentioned it was tested on my Z1. I'm gonna try to do https://github.com/postmarketOS/pmbootstrap/issues/464

**Pull request merged**
