### PR TITLE
fix network manager

### PR DESCRIPTION
**Pull request by bhush9**
For Networkmanager problems reported in IRC... untested but should fix all issues I am sure.

Please don't squash :)

---
[ ] Merge on GitHub (see <https://postmarketos.org/merge>)

### CODE REVIEW

**Comment by bhush9** [comment]
hm.. that's curious error, there exists no plugdev group.. not sure what should create that group?

**Comment by PureTryOut** [comment]
@MartijnBraam (or anyone else with a working device with wifi) any chance you could test this?

**Comment by ollieparanoid** [comment]
Rebased to master.

@PureTryOut, @montvid: I wonder if this fixes the bad wifi you've described in #1547. Could you possibly test that?

**Comment by montvid** [comment]
Tested this pull. Well it does no harm for asus-flo maybe less dropped packages but overall the wifi still has problems:

--- 8.8.8.8 ping statistics ---
50 packets transmitted, 49 packets received, 2% packet loss
round-trip min/avg/max = 168.246/521.382/1146.132 ms
vs
--- 8.8.8.8 ping statistics ---
12 packets transmitted, 10 packets received, 16% packet loss
round-trip min/avg/max = 208.455/655.699/1208.758 ms

**Comment by montvid** [comment]
Cmon' guys are still fixing a driver bug for 2 years 2016-2018 :) Oh I will wait :) 
i see this a lot https://bugs.96boards.org/show_bug.cgi?id=319
https://patchwork.kernel.org/patch/10338447/

**Comment by PureTryOut** [comment]
@ollieparanoid sadly it doesn't fix the networking issue on the RPi. Note, the issue there is networking in general, not just wifi.

**Comment by ollieparanoid** [comment]
@montvid, @PureTryOut: Thanks for testing. Right, I got a bit confused, initially #1547 was about bad networking on the RPi, then @montvid joined in with the asus-flo wifi only problems. I'll split the issue to make it less confusing.


Merging this, since @montvid confirmed that it didn't introduce a new bug on his device.

**Comment by ollieparanoid** [comment]
Merged in ea03a32298c896e507253968042d699e0a882eee and 26808e4d6a20e4e852416875a7578a9688ccf073.

**Pull request closed without merging**
