### PR TITLE
Adds fastboot flasher "format".

### PR DESCRIPTION
**Pull request by MoreRobustThanYou**
It formats boot, system, userdata, and cache.

### CODE REVIEW

**Comment by ollieparanoid** [comment]
Thanks for the contribution! As the Travis job points out, the syntax needs to be adjusted to be pep8 compliant. Either manually fix what it suggests, or run `autopep8` on the file (I always do the latter one, it's much easier 😄 ).

**Comment by MoreRobustThanYou** [comment]
@ollieparanoid done.

**Comment by ollieparanoid** [comment]
Have you tested this? It doesn't work for me:

`pmbootstrap flasher format`

```
usage: pmbootstrap flasher [-h] [--method FLASH_METHOD]
                           {boot,flash_kernel,flash_system,sideload,list_flavors,list_devices,export}
                           ...
pmbootstrap flasher: error: argument action_flasher: invalid choice: 'format' (choose from 'boot', 'flash_kernel', 'flash_system', 'sideload', 'list_flavors', 'list_devices', 'export')
```

**Comment by MoreRobustThanYou** [comment]
@ollieparanoid Woops! Forgot to add it to the frontend! Gimme a sec.

**Comment by ollieparanoid** [comment]
Nope, it still gives **the same** error. Please test all changes locally, even if they appear to be small and working for sure. The correct workflow would be:
1. make the change in the source
2. test it, in this case: run `pmbootstrap flasher format` with an attached device and check if it was formatted successfully
3. report that it's ready to be tested and reviewed.

The names of the branches look like, you've been editing the scripts in GitHub's text editor, which would explain why nothing is tested. Testing PRs takes a lot of time on our end, in which we can't do other postmarketOS related stuff, so **please try not ask us to merge stuff which you didn't test!**

But don't get discouraged by this. You can get used to testing your stuff locally and using git with multiple branches, we'll even help you with that. And once you have it, you'll be able to make bigger and bigger changes safely. Maybe one day you'll be able to implement the LVM stuff for example.

**Pull request closed without merging**
