### PR TITLE
Patch KWIN to support amazon-thor

### PR DESCRIPTION
**Pull request by MoreRobustThanYou**
```amazon-thor```'s framebuffer uses some weird framebuffer format, so I updated the kwin patch to support it.

Touch doesn't work?

### CODE REVIEW

**Comment by MoreRobustThanYou** [comment]
Logread: https://pastebin.com/rVdvJxzg

**Comment by PureTryOut** [comment]
Not sure if I'm a fan of editing the original patch. Could you try to add it as a separate patch instead? Because I'm assuming your patch doesn't add support for "RGB32 framebuffer with BGR order" but rather some other format.

**Comment by MoreRobustThanYou** [comment]
K

**Comment by MoreRobustThanYou** [comment]
Didn't mean to close this, woops.

**Comment by bhush9** [comment]
@MoreRobustThanYou have you confirmed that it works on your device and colors are correct?

**Comment by MoreRobustThanYou** [comment]
yes

**Comment by MartijnBraam** [comment]
Its very weird that we have two Format_RGBA8888 blocks in the fbdev driver, with one being RGBA and one being actually ABGR, and you don't check for the alpha channel offset.

If the colors are correct with this patch it means that the driver expects RGBA but advertises ABGR in which case the fbdev driver needs a patch (like hammerhead)

**Comment by ollieparanoid** [comment]
@MoreRobustThanYou: thanks for making the PR!

What @MartijnBraam sounds logical though, what happens when you use the [06_fix_mdss_fb_rgb_mode.patch](https://wiki.postmarketos.org/wiki/Troubleshooting:display#Kernel_patch) from hammerhead? (I think you've mentioned at some point in IRC that you tested the patch already to fix X11?)

**Comment by MoreRobustThanYou** [comment]
img_20180223_122439_1

**Comment by MartijnBraam** [comment]
Yep the colors are incorrect, see the settings icon in this image: https://wiki.postmarketos.org/wiki/File:Galaxy-nexus-plasma.jpg

**Comment by astralloop** [comment]
@MartijnBraam I will note that pic was taken with the kernel patch, not the kwin patch

**Comment by MoreRobustThanYou** [comment]
@MartijnBraam I will note that pic was taken with the kernel patch, not the kwin patch

**Comment by ollieparanoid** [comment]
Closing, as you've fixed the kernel in #1252.
@MoreRobustThanYou: thanks for your work on this!

**Pull request closed without merging**
