### PR TITLE
Fix regex in recovery installer

### PR DESCRIPTION
**Pull request by ata2001**
It was able to parse the fstab on sony-amami.

### CODE REVIEW

**Comment by lduboeuf** [comment]
not sure if i'm doing right for testing. Anything to do on device ?

I fetched the pull request locally and switched to the PR branch,
pmbootstrap zap
pmbootsrap init
pmbootstrap install --no-fde --android-recovery-zip
install android-recovery.zip via TWRP
Same error occured: https://bpaste.net/show/36b2948edd95

**Comment by ollieparanoid** [comment]
Thanks for making the PR @ata2001 and for testing @lduboeuf!
In your log, there's this line:
> tar: skipping unsafe symlink to '/bin/busybox' in archive, set EXTRACT_UNSAFE_SYMLINKS=1 to extract

Which is bug #1333, and the fix for it was just merged to `master` (but it is not included in this PR yet).

@lduboeuf: you could try if the version from `master` works if you want to, I'm not sure if the fix from this PR is still needed (but @ata2001 could probably answer this). If the version from `master` does not work, we need to rebase this PR on master and then try it again.

**Comment by lduboeuf** [comment]
no more `dd: can't open '/dev/block/mmcblk0p5` with master but still have 

> tar: skipping unsafe symlink to '/bin/busybox' in archive, set EXTRACT_UNSAFE_SYMLINKS=1 to extract

but maybe i missed something because i have lines like this:

> Error: Partition(s) 1, 2, 3, ... on /dev/block/mmcblk0p9 have been written, but we have been unable to inform the kernel of the change, probably because it/they are in use.  As a result, the old partition(s) will remain in use.  You should reboot now before making further changes.
> + parted -s /dev/block/mmcblk0p9 'set 1 boot on'

**Comment by drebrez** [comment]
@ollieparanoid I think that here it's not a `tar` related problem. It was discovering 2 partition for the `/boot`, see old log:
```
+ awk /^\/boot/ {print $3} /recovery.fstab
+ _BOOT_PARTITION=/dev/block/mmcblk0p5
/dev/block/mmcblk0p2
+ [ ! -z /dev/block/mmcblk0p5
/dev/block/mmcblk0p2 ]
+ echo boot partition found at /dev/block/mmcblk0p5
/dev/block/mmcblk0p2
boot partition found at /dev/block/mmcblk0p5
/dev/block/mmcblk0p2
+ export BOOT_PARTITION=/dev/block/mmcblk0p5
/dev/block/mmcblk0p2
```
@ata2001 rewrote the `awk` command and in the last log that @lduboeuf posted it seems fixed.
@lduboeuf the error about unable to inform the kernel is misleading, it is more a warning than an error. You can ignore it.

**Comment by ata2001** [comment]
Now that I've merged master, the tar error should be gone too. As drebrez said, just ignore the parted error, it gets printed on most devices even if it successfully creates the partitions.

@ollieparanoid This patch is still necessary, the old regex matched everything that starts with /boot.

**Pull request merged**
