### PR TITLE
Add kernel modules to device Samsung i9070

### PR DESCRIPTION
**Pull request by drebrez**
Add the compilation/installation of the kernel modules containing the wifi firmware from the vendor files repository.
Also add the modules-load.conf file to specify that the wifi module should be loaded at boot time.

### CODE REVIEW

**Comment by drebrez** [comment]
@MartijnBraam Sure I can move it, it was the same location as in the vendor files repository.
Is it ok to have subfolders there? like `/lib/firmware/wifi` ?

**Comment by MartijnBraam** [comment]
You can create subdirectories, but in the upstream firmware package the broadcom drivers into `/lib/firmware/brcm`

**Comment by drebrez** [comment]
@MartijnBraam you mean I have to move them from `/lib/firmware/wifi` to `/lib/firmware/brcm`?

**Comment by MartijnBraam** [comment]
It doesn't matter that much, I let @ollieparanoid decide. Maybe we should use /lib/fimware/pmos to avoid (future) conflicts with the linux-firmware package

**Comment by ollieparanoid** [comment]
I like, that you've included the usual comment at the beginning of `modules-load.conf` and how you made small patches for the firmware paths :+1:

You have changed tabs to spaces in the `APKBUILD`s. Please don't do that, it makes the diff hard to read. In this pull request, and also when comparing to Alpine's original `APKBUILD` (in case of `linux-samsung-i9070` vs. `linux-vanilla`). Furthermore I'd like to have the `APKBUILD`s (and shell scripts) follow the same formatting style throughout the entire code base, so it looks consistent. (For Python we already follow the PEP8 standard - which actually uses whitespaces instead of tabs - and TravisCI checks for that. If you want to automatically format your `APKBUILD`s/shell scripts before making a PR, I recommend [shfmt](https://github.com/postmarketOS/pmbootstrap/issues/110) - and we might create automatized checks for that, too).

About the firmware path for `bcmdhd_sta.bin`: I'd prefer the non-conflict solution with `/lib/firmware/postmarketos/`.

I am not sure about the best location for the `nvram_net.txt`. If we treat it  like a config file, it should go to a folder in `/etc/`. I've seen, that you can configure the [mac address](https://github.com/Epirex/android_vendor_samsung_u8500/blob/cm-13.0/janice/system/etc/wifi/nvram_net.txt#L13) there? But then again, network managers and tools like `macchanger` (packaged for Alpine) should be able to [set the mac](https://github.com/alobbs/macchanger/blob/master/src/netinfo.c#L93) to any value at runtime, without touching that config file - the standard way it works for all Linux wifi drivers. So if users don't need to change this file at all, I think we should also put it to `/lib/firmware/postmarketos/`. If you want to, you could try whether the `macchanger` tool is working on your phone, to help making this decision. What do you guys think about this?

I like, that you have added a colorized prompt to the shell in `profile.sh`. But if we do that in the device-specific package, it will look different for every device, or be lots of maintenance effort to keep in sync between the packages. So how about putting that in `postmarketos-base` instead? We could even put a  generic "battery" function in there, if we put the path to the battery in the 
deviceinfo file. I suggest discussing this in a separate issue/PR.

One more thing, I realize, that there are aliases, that are user specific, such as 'ping -c 5', I haven't seen that before, but I can understand if that is useful for you. Maybe we could add a mechanism, so that you could include your user-specific configs during `pmbootstrap install` in the root image, but it does not get versioned along with pmbootstrap, such as a creating a user-specific package and blacklisting that in the gitignore? This also needs more discussion in a separate issue.

**Thank you very much for your hard work on this. It's obvious, that you know what you are doing and this wifi support alone brings the project forward by a great deal!**

PS: Why have you *reduced* the lzo compression, is it to save time during package building?

**Comment by drebrez** [comment]
> You have changed tabs to spaces in the APKBUILDs.

I wasn't sure about it, I followed the Python standard. 
But I will revert it back to tabs.
(an automated check will be useful)

> About the firmware path for bcmdhd_sta.bin: I'd prefer the non-conflict solution with /lib/firmware/postmarketos/.

I'm fine, I will change it. 
Same question again, should we structure the firmware files in subfolders there? 
And for the wifi is better to have a generic `wifi` folder or we should use a `brcm` folder?

> I am not sure about the best location for the nvram_net.txt. If we treat it like a config file, it should go to a folder in /etc/. I've seen, that you can configure the mac address there?

For me make sense to leave it beside the firmware, since users doesn't have to change it. 
The mac address specified there seems ignored because when I load the module and bring the wlan0 interface up, the mac address is 00:00:00:00:00. I'm not sure why.
I will try to see if the `macchanger` tool works.

> profile.sh

I can remove it from this PR and we can discuss about putting a generic profile script in postmarketos-base

> battery function

Same as the profile script, I will remove it and we can create an issue/PR to discuss it. (maybe is related to #88)

> Why have you reduced the lzo compression, is it to save time during package building?

There is a comment about it in the APKBUILD, it's because the `lzop` inside the chroot was throwing and error during the compilation. This was in the armhf chroot, didn't tried if there is the same issue now that I changed it back to native chroot. Is the busybox installed there the same? 
It depends how the busybox was built (https://github.com/mirror/busybox/blob/master/archival/lzop.c#L1058-L1068)

**Comment by ollieparanoid** [comment]
> Same question again, should we structure the firmware files in subfolders there?
> And for the wifi is better to have a generic wifi folder or we should use a brcm folder?

I think doing it without subfolders is enough. Then we don't need to think about the correct subfolder name, and we should not have many files in there anyway (before we get to mainline kernels, it will only be all firmware files for one device).

> For me make sense to leave it beside the firmware, since users doesn't have to change it.

:+1: (Trying out `macchanger` isn't necessary anymore, because you've already said, that the mac address configured in that file does not matter.)

> `lzop`

I've overlooked the comment. Thanks for sharing the link to the source. Yes, busybox in `x86_64` is compiled with the same config, as the `armhf` version in Alpine.

**Pull request merged**
